# -*- coding: utf-8 -*-
"""
/***************************************************************************
 KVM
                                 A QGIS plugin
 Kinematic Velocity Modelling
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2025-04-18
        copyright            : (C) 2025 by Anonymous
        email                : Anonymous@hotmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import subprocess
import sys
from qgis.PyQt.QtWidgets import QMessageBox
from qgis.utils import iface

PANDAS_PACKAGE = "pandas"

class MissingDependencyError(Exception):
    """It is triggered when a critical plugin dependency is missing."""
    pass

def ensure_pandas_installed():
    """
    Try importing pandas; if it doesn't exist, try installing it with pip.
    If the installation fails, display a message and return False.
    """
    try:
        import pandas as pd # noqa: F401
        return True
    except ImportError:
        # Try instal con pip
        try:
            # Use the same QGIS interpreter
            cmd = [
                sys.executable,
                "-m",
                "pip",
                "install",
                "--user",
                PANDAS_PACKAGE,
            ]
            proc = subprocess.run(
                cmd,
                stdout=subprocess.PIPE,
                stderr=subprocess.PIPE,
                text=True,
            )
            if proc.returncode != 0:
                # Installation failed
                raise RuntimeError(proc.stderr)
        except Exception as e:
            # Mostrar mensaje y abortar
            msg = (
                "The plugin requires the 'pandas' library and could not be installed "
                "install automatically.\n\n"
                "Please install 'pandas' manually in the environment of "
                "PQGIS Python before reinstalling/activating the plugin.\n\n"
                f"Technical detail: {e}\n\n"
                "Or install a version of QGIS (3.30.00) or higher."
            )
            QMessageBox.critical(
                iface.mainWindow(),
                "Error installing dependency",
                msg,
            )
            
            # Lanzamos excepción para que QGIS no continúe con la carga
            raise MissingDependencyError("Pandas could not be installed") from e

        # Try importing again after installation
        try:
            import pandas as pd # noqa: F401
            return True
        except ImportError as e:
            msg = (
                "An attempt was made to install 'pandas', but they still cannot be imported.\n\n"
                "Install 'pandas' manually in the QGIS environment "
                "before using this add-on.\n"
                "Or install a version of QGIS (3.30.00) or higher."
            )
            QMessageBox.critical(
                iface.mainWindow(),
                "Error loading dependency",
                msg,
            )
            raise MissingDependencyError("pandas sigue sin poder importarse") from e

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name

    # If the dependency is missing, an exception is thrown and QGIS does not create the instance.
    ensure_pandas_installed()

    """Load KVM class from file KVM.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .KVM import KVM
    return KVM(iface)
